"""Tests for init-kernel output conventions.

Verifies that files generated by the init-kernel skill are compatible
with evaluate.py function discovery, config validation, and mutation
extraction.
"""
import ast
import os
import sys
import tempfile
import textwrap
import types
import unittest.mock

import pytest
import yaml

from kernel_evolve.config import load_config, EvolveConfig
from kernel_evolve.mutation import extract_evolve_block


def _make_jax_stubs():
    """Return a namespace dict with stub jax modules so exec() works without jax installed."""
    jax_mod = types.ModuleType("jax")
    jnp_mod = types.ModuleType("jax.numpy")

    # Minimal stubs needed by the sample code
    jax_mod.numpy = jnp_mod
    jax_mod.random = types.SimpleNamespace(
        PRNGKey=lambda seed: None,
        normal=lambda key, shape, dtype=None: None,
    )
    jax_mod.ShapeDtypeStruct = lambda shape, dtype: None
    jax_mod.block_until_ready = lambda x: x
    jax_mod.devices = lambda: []
    jax_mod.default_backend = lambda: "cpu"
    jnp_mod.sum = lambda x, **kw: 0.0
    jnp_mod.bfloat16 = "bfloat16"

    pallas_mod = types.ModuleType("jax.experimental.pallas")
    pallas_mod.pallas_call = lambda fn, **kw: (lambda *a, **kw2: None)
    pallas_mod.BlockSpec = lambda *a, **kw: None
    pltpu_mod = types.ModuleType("jax.experimental.pallas.tpu")

    jax_experimental = types.ModuleType("jax.experimental")
    jax_experimental.pallas = pallas_mod
    jax_mod.experimental = jax_experimental

    return {
        "jax": jax_mod,
        "jnp": jnp_mod,
    }


def _exec_with_jax_stubs(code: str) -> dict:
    """exec() code string with jax stub modules injected, returns namespace."""
    stubs = _make_jax_stubs()
    # Patch sys.modules so that import statements inside exec() resolve to stubs
    patch_targets = {
        "jax": stubs["jax"],
        "jax.numpy": stubs["jnp"],
        "jax.experimental": stubs["jax"].experimental,
        "jax.experimental.pallas": stubs["jax"].experimental.pallas,
        "jax.experimental.pallas.tpu": types.ModuleType("jax.experimental.pallas.tpu"),
    }
    with unittest.mock.patch.dict(sys.modules, patch_targets):
        ns = {}
        exec(code, ns)
    return ns


# --- Ref file conventions ---

SAMPLE_REF = textwrap.dedent('''\
    # Source: primatrix/pallas-kernel @ branch: main
    # Commit: abc1234
    # Initialized: 2026-03-31
    """Reference kernel for sample_kernel."""

    import jax
    import jax.numpy as jnp


    def _make_test_data(M=1024, N=1024):
        x = jax.random.normal(jax.random.PRNGKey(0), (M, N), dtype=jnp.bfloat16)
        return x


    def simple_compute(M=1024, N=1024):
        x = _make_test_data(M, N)
        return jnp.sum(x)


    def reference_fn(**kwargs):
        return simple_compute(**kwargs)
''')


def test_ref_has_valid_syntax():
    """Ref files must be valid Python."""
    ast.parse(SAMPLE_REF)


def test_ref_simple_compute_discoverable():
    """evaluate.py discovers simple_compute via exec()."""
    ns = _exec_with_jax_stubs(SAMPLE_REF)
    assert callable(ns.get("simple_compute"))


def test_ref_reference_fn_discoverable():
    """evaluate.py discovers reference_fn via exec()."""
    ns = _exec_with_jax_stubs(SAMPLE_REF)
    assert callable(ns.get("reference_fn"))


def test_ref_has_source_traceability():
    """Ref files must include source metadata comments."""
    assert "# Source: primatrix/pallas-kernel" in SAMPLE_REF
    assert "# Commit:" in SAMPLE_REF
    assert "# Initialized:" in SAMPLE_REF


# --- Template file conventions ---

SAMPLE_TEMPLATE = textwrap.dedent('''\
    """Sample kernel template for evolutionary optimization."""

    import jax
    import jax.numpy as jnp
    from jax.experimental import pallas as pl
    from jax.experimental.pallas import tpu as pltpu


    def _make_test_data(M=1024, N=1024):
        x = jax.random.normal(jax.random.PRNGKey(0), (M, N), dtype=jnp.bfloat16)
        return x


    # EVOLVE-BLOCK-START
    def _kernel_body(x_ref, o_ref):
        o_ref[...] = x_ref[...] * 2


    def optimized_compute(M=1024, N=1024):
        x = _make_test_data(M, N)
        result = pl.pallas_call(
            _kernel_body,
            out_shape=jax.ShapeDtypeStruct((M, N), jnp.bfloat16),
            in_specs=[pl.BlockSpec((M, N), lambda: (0, 0))],
            out_specs=pl.BlockSpec((M, N), lambda: (0, 0)),
        )(x)
        return jnp.sum(result)
    # EVOLVE-BLOCK-END
''')


def test_template_has_valid_syntax():
    """Template files must be valid Python."""
    ast.parse(SAMPLE_TEMPLATE)


def test_template_optimized_compute_discoverable():
    """evaluate.py discovers optimized_compute via exec()."""
    ns = _exec_with_jax_stubs(SAMPLE_TEMPLATE)
    assert callable(ns.get("optimized_compute"))


def test_template_evolve_block_extractable():
    """Mutation system can extract the EVOLVE-BLOCK."""
    block = extract_evolve_block(SAMPLE_TEMPLATE)
    assert len(block) > 50
    assert "optimized_compute" in block
    assert "_kernel_body" in block


def test_template_imports_outside_evolve_block():
    """Imports must be outside the EVOLVE-BLOCK to remain frozen."""
    lines = SAMPLE_TEMPLATE.split("\n")
    start_idx = next(i for i, l in enumerate(lines) if "EVOLVE-BLOCK-START" in l)
    pre_block = "\n".join(lines[:start_idx])
    assert "import jax" in pre_block
    assert "from jax.experimental import pallas" in pre_block


def test_template_make_test_data_outside_evolve_block():
    """_make_test_data must be outside EVOLVE-BLOCK to remain frozen."""
    lines = SAMPLE_TEMPLATE.split("\n")
    start_idx = next(i for i, l in enumerate(lines) if "EVOLVE-BLOCK-START" in l)
    pre_block = "\n".join(lines[:start_idx])
    assert "_make_test_data" in pre_block


# --- YAML config conventions ---

SAMPLE_CONFIG = {
    "kernel": {
        "name": "sample_kernel",
        "template": "kernels/sample_kernel.py",
        "reference": "kernels/sample_kernel_ref.py",
        "evolve_markers": {
            "start": "# EVOLVE-BLOCK-START",
            "end": "# EVOLVE-BLOCK-END",
        },
    },
    "shapes": [{"M": 1024, "N": 1024}],
    "correctness": {"method": "allclose", "rtol": 1e-2, "atol": 1.0},
    "evaluator": {
        "namespace": "default",
        "job_template": ".github/ci/kernel-eval-job.yaml",
        "repo": "sii-xinglong/Glaucis",
        "branch": "main",
        "poll_interval": 15,
        "timeout": 600,
    },
    "tpu": {"cluster": "tpu7x-cluster", "zone": "us-central1"},
    "batch": {"variants_per_round": 5, "top_k": 2, "max_active_lineages": 4},
    "session": {"max_iterations": 20, "output_dir": "runs/sample_kernel"},
}


def test_config_validates_against_schema():
    """Generated YAML must validate against EvolveConfig Pydantic schema."""
    config = EvolveConfig(**SAMPLE_CONFIG)
    assert config.kernel.name == "sample_kernel"
    assert config.kernel.template == "kernels/sample_kernel.py"
    assert config.kernel.reference == "kernels/sample_kernel_ref.py"
    assert len(config.shapes) == 1
    assert config.batch.variants_per_round == 5


def test_config_yaml_roundtrip():
    """Generated YAML can be written and loaded back via load_config."""
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".yaml", delete=False
    ) as f:
        yaml.dump(SAMPLE_CONFIG, f)
        f.flush()
        try:
            config = load_config(f.name)
            assert config.kernel.name == "sample_kernel"
        finally:
            os.unlink(f.name)


def test_config_rejects_extra_fields():
    """EvolveConfig uses extra='forbid' — extra fields must cause validation error."""
    bad_config = {**SAMPLE_CONFIG, "unknown_field": "value"}
    with pytest.raises(Exception):
        EvolveConfig(**bad_config)


# --- Standalone test conventions ---

SAMPLE_STANDALONE_TEST = textwrap.dedent('''\
    """Standalone accuracy comparison test for sample_kernel.

    Run on TPU:
        python tests/standalone_sample_kernel_test.py

    Verifies:
      1. Both template and reference produce finite results
      2. Template matches reference within atol
      3. Measures forward latency
    """
    import time
    import sys
    import numpy as np

    import jax
    import jax.numpy as jnp


    def main():
        print(f"JAX devices: {jax.devices()}")
        print(f"Platform: {jax.default_backend()}")

        tmpl_ns = {}
        ref_ns = {}
        exec(open("examples/kernels/sample_kernel.py").read(), tmpl_ns)
        exec(open("examples/kernels/sample_kernel_ref.py").read(), ref_ns)

        shapes = {"M": 1024, "N": 1024}
        print(f"Shapes: {shapes}")

        print("--- Correctness ---")
        tmpl_out = tmpl_ns["optimized_compute"](**shapes)
        ref_out = ref_ns["simple_compute"](**shapes)
        jax.block_until_ready(tmpl_out)
        jax.block_until_ready(ref_out)

        max_diff = float(np.max(np.abs(np.array(tmpl_out) - np.array(ref_out))))
        print(f"Max diff: {max_diff:.6e}")

        if max_diff > 1.0:
            print(f"FAIL: max_diff {max_diff} > atol 1.0")
            sys.exit(1)
        print("PASS: correctness within tolerance")


    if __name__ == "__main__":
        main()
''')


def test_standalone_test_has_valid_syntax():
    """Standalone test files must be valid Python."""
    ast.parse(SAMPLE_STANDALONE_TEST)


def test_standalone_test_uses_exec_pattern():
    """Standalone tests must load kernels via exec() pattern."""
    assert 'exec(open(' in SAMPLE_STANDALONE_TEST
    assert 'optimized_compute' in SAMPLE_STANDALONE_TEST
    assert 'simple_compute' in SAMPLE_STANDALONE_TEST


def test_standalone_test_has_main_guard():
    """Standalone tests must have __main__ guard."""
    assert 'if __name__ == "__main__"' in SAMPLE_STANDALONE_TEST
